### ISSUE TITLE
After a database lock is minimized. You can still see the password by matching the site information with the shortcut key

### ISSUE THREAD

**Issue by vipei** [Rookiestyle/LockAssist#10]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

## Context
[NOTE]: # (Provide any additional information you may have)
OS: 
KeePass Version:2.49
Plugin Version:3.2

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)
After a database lock is minimized. You can still see the password by matching the site information with the shortcut key

![1](https://user-images.githubusercontent.com/49584327/148655565-db691630-1def-4d80-a14f-cae97684e410.gif)

**Comment by vipei** [comment]
![1](https://user-images.githubusercontent.com/49584327/148656162-bf4ff60f-e741-406d-8e93-0b63eb1398cf.gif)
The keepASSOtp.plgx plug-in is used to display oTP entries through the Keepass icon on the taskbar after the database is minimized and locked

**Comment by Rookiestyle** [comment]
Long story short: This is the intended behaviour when SoftLock is active and won't be changed


> After a database lock is minimized. You can still see the password by matching the site information with the shortcut key

It is KeePass standard to show the password in this window and my plugin does not change this.
When SoftLock is active, Auto-Type can still be used. That is the intended behaviour.

> The keepASSOtp.plgx plug-in is used to display oTP entries through the Keepass icon on the taskbar after the database is minimized and locked

Your database is *not* locked. SoftLock does not change other plugins' behaviour.
This is already mentioned in LockAssist's readme:
https://github.com/Rookiestyle/LockAssist#softlock
> SoftLock hides sensitive information while still allowing Auto-Type as well as other integration.

https://github.com/Rookiestyle/LockAssist/wiki/SoftLock---Privacy-mode
This wiki contains a bit more information.

**Comment by vipei** [comment]
So this minimization lock is not secure, but it looks useful

**Comment by Rookiestyle** [comment]
SoftLock does not lock the database because this is something KeePass already allows you to do.

SoftLock offers a *privacy mode* that will *hide* this information if e. g. you leave your pc unattended, forget to lock your database or you are editing an entry (KeePass' lock won't work in that case).
Nobody can see all the passwords (in Auto-Type entry selection you can hide the password column) and nobody can export your database to csv or similar.

If you don't want that, deactivate SoftLock. You can still use Quick Unlock.
