### ISSUE TITLE
Lock workspace - Open all loaded databases 

### ISSUE THREAD

**Issue by M-0ss** [Rookiestyle/LockAssist#11]
## Overview

[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)
When It is Lock workspace is active and not, all databases databases are unlocked after use the quick unlock PIN. Also the [Shift] key doesn't work too in the KeePass Version: 2.53. 

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Minimize two data bases 
2. Untray Keepass
3. Insert one PIN
4. The two bases will be unlocked. 

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

## Context
[NOTE]: # (Provide any additional information you may have)
OS: 
KeePass Version: 2.53
Plugin Version: 3.2.2.0

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)
[Debug.pdf](https://github.com/Rookiestyle/LockAssist/files/10981940/Debug.pdf)

**Comment by Rookiestyle** [comment]
Does your issue refer to Quick Unlock or to Softlock?
What happens if you enter a wrong PIN?

**Comment by M-0ss** [comment]
The main problem is when the "Global 'Lock warkspace/unlock Workspace' option is not active and using the PIN to open a base opens that base and the rest of the bases. 

if I use the wrong pin it does not open any bases. That is ok. 

![Captura de pantalla 2023-03-16 084819](https://user-images.githubusercontent.com/127971564/225549503-c2f0ac07-0b95-4adc-8a3a-1d3040390a1d.jpg)

**Comment by Rookiestyle** [comment]
> SoftLock hides sensitive information while still allowing Auto-Type as well as other integration.

SoftLock does **not** lock the databases (would stop Auto-Type from working) and SoftLock is not specific for databases but affects KeePass overall.
Either information is hidden or not.

To verify, please actually lock the two databases and try again. The window where you enter the PIN should be called *Quick Unlock* and it should work in the way you expected it

**Comment by M-0ss** [comment]
![Captura de pantalla 2023-03-16 111615-Prueba](https://user-images.githubusercontent.com/127971564/225590275-327c82a2-de45-4b51-bec3-47ed7c25ac08.jpg)
My mistake. 

I thought that with SoftLock the keepass information was hidden but when using the PIN it only showed the base information of that PIN not the other bases. 

If it could be added it would be a great improvement. 

Thank you very much for the clarification.

**Comment by Rookiestyle** [comment]
SodtLock hides the sensitive parts of the KeePass window and this cannot be restricted to only some of the databases. It is not possible to have different SoftLock status for specific databases.

You can always lock / unlock specific databases and in that case, Quick Unlock and Global lock workspace will be considered. 

Main differences between SoftLock and Quick Unlock
* SoftLock hides sensitive parts of the KeePass windows and this affects all databases that are loaded
* SoftLock does not lock databases, e. g. Auto-Type is still possible
* Quick Unlock makes it easier to unlock a locked database - You can lock databases manually or use KeePass options to lock them when minimizing, idle time, .. 
* Locked database = Complete content of database is removed from memory; Auto-Type, ... is NOT possible
