### ISSUE TITLE
Automatisches Schließens von KeePass

### ISSUE THREAD

**Issue by r2d2z** [Rookiestyle/LockAssist#12]
Transferiert von EarlyUpdateCheck 28.04.2023 - ~ 14:00 Uhr:

Hallo Rookiestyle,
anders als dargelegt sperrt LockAssist-Plugin ein einmal falsch eingegebenes "Kurzpasswort" bei mir nicht (Keepasss 2.53.1 unter Windows 10). Ich kann das mehrfach fehlerhaft eingeben. Wenn ich, abgesehen von der Zeitsperre, dann das Kurzpasswort richtig eingebe, funktioniert dieses immer noch. Das konterkariert natürlich den Passswort-Safe.

Viele Grüße
R2D2Z

28.04.2023 - 15:19 Uhr:
@r2d2z
    Bitte lege ein Issue im richtigen Repository an, hier also in dem für LockAssist
    Gib mir da bitte die Info mit, wie das Fenster heißt, in das du die Pin eingibst. "Quick Unlock" oder "SoftLock"?

Hallo Rookiestyle,
Ausgangspunkt meines Problems war, dass Keepass bei einem geöffneten Eintrag nicht automatisch schließt.

Der Programmierer von Keepass hat mir erläutert, dass ein automatisches Schließen mit Problemen verbunden sei (z.B. sollen zwischenzeitliche Änderungen gespeichert werden oder nicht?). Er hatte auf Ihr PlugIn LockAssist, und hier auf den Softlock-Modus verwiesen.

Auf Ihren Hinweis hin ergibt sich nach Recherche: Im Softlock-Modus schließt das PlugIn zwar die Oberfläche. Gleichwohl kann man das Programm aber mit dem Kurzkennwort auch nach fehlerhafter Eingabe wieder öffnen.
Im Quick Unlock-Modus schließt das Programm die Oberfläche leider auch nicht, wenn ein Eintrag geöffnet ist.

Ich hatte gehofft, dass über das Ablaufdatum von Quick Unlock auch die Zeit für den Softlock-Modus begrenzt ist. Funktioniert aber leider nicht.

Haben Sie eine Lösung?

Vielen Dank!

R2D2Z

**Comment by Rookiestyle** [comment]
> Ich hatte gehofft, dass über das Ablaufdatum von Quick Unlock auch die Zeit für den Softlock-Modus begrenzt ist. Funktioniert aber leider nicht. 

Also Softlock ist aktiv und das Ablaufdatum von Quick Unlock ist erreicht? Was sollte dann passieren?

Ein Sperren der Datenbank ist nicht möglich, wenn ein Eintrag geöffnet ist.

**Comment by r2d2z** [comment]
Hallo Rookiestyle,

vielen Dank für die rasendschnelle Antwort!!

"Also Softlock ist aktiv und das Ablaufdatum von Quick Unlock ist erreicht? Was sollte dann passieren?"

Was spricht dagegen, dass in dieser Situation KeePass nur noch mit dem Masterpasswort wieder geöffnet werden kann, sozusagen ein ,Metastatus' zwischen vollständiger Sperrung und Öffnungsmöglichkeit mit dem Kurzpasswort.

In dieser Situation ist beim jetzigen Status die Sicherheit gefährdet, denn das Argument "It might be easier to crack a 4 character Quick Unlock key than a e. g. 30 character master password but if you don't succeed th very first time... there is no 2nd try." greift nicht mehr.

R2D2Z

**Comment by Rookiestyle** [comment]
Bei Softlock ist die Datenbank weiterhin geöffnet, sonst wären Autotype & Co. nicht möglich.
Das ist aus meiner Sicht etwas grundsätzlich anderes als das Öffnen einer geschlossenen Datenbank.

Ich schaue mal, ob ich deine Idee umsetzen kann - bin mir allerdings nicht sicher, eben weil die Datenbank ja nicht geschlossen ist. Wenn es geht, dann wird das ein eigener Tmeout für Softlock werden.

**Comment by r2d2z** [comment]
Hallo Rookiestyle,

mein Problem ist, dass ich in Keepass nicht nur Passwörter habe, sondern auch Notizen zu einzelnen Accounts. Deswegen mache ich die Einträge häufig auf und vergesse sie zu schließen. Dann steht die gesamte Datenbank offen. Bei Verbindung des Rechners mit dem Internet ist mir der Gedanke unheimlich.
Beim Draufrumdenken: Was spricht eigentlich dagegen, wenn man in Softlock das gleiche Passwort wie das Hauptpasswort eingibt?

R2D2Z

**Comment by Rookiestyle** [comment]
> mein Problem ist, dass ich in Keepass nicht nur Passwörter habe, sondern auch Notizen zu einzelnen Accounts. Deswegen mache ich die Einträge häufig auf und vergesse sie zu schließen. Dann steht die gesamte Datenbank offen.

Du kannst bereits in KeePass selbst, also ohne Plugins, Notizen anzeigen lassen: `View -> Show Entry View` bzw. `Ansicht -> Eintragsansicht anzeigen`
Zusätzlich gibt es Plugins, die dir hierbei helfen, bspw. KPEnhancedEntryView
Einträge sollten nur zum Bearbeiten geöffnet werden.

> Dann steht die gesamte Datenbank offen. Bei Verbindung des Rechners mit dem Internet ist mir der Gedanke unheimlich.

Nochmal: Softlock schließt die Datenbank nicht. Es verbirgt ihren Inhalt lediglich vor jemandem, der an deinem nicht gesperrten Rechner vorbeiläuft. "Dem Internet" ist das egal.

Die Idee, nach einer definierbaren Zeit das DB-Password abzufragen finde ich losgelöst davon sinnvoll.
Versuche mal [Version 3.2.2.1](https://github.com/Rookiestyle/LockAssist/releases/tag/untagged-86e695aefb77bfb5dc7f).
Wenn das bei dir funktioniert, veröffentliche ich es als Update für alle.
**Wichtige Einschränkung** Genauso wie die Quick Unlock Option "Database password" gelten auch hier diese Voraussetzungen:
* Database masterkey contains a password
* Option 'Remember master password' is active
[Wiki](Database password mode)

**Comment by r2d2z** [comment]
Hallo Rookiestyle,
die Eintragsansicht habe ich tatsächlich immer geöffnet. Ist mir jedoch noch nie aufgefallen. Wie blöd ich doch bin. Vielen Dank für den Tip!!

"Dem Internet" ist das egal: Ich als Laie habe kein gutes Gefühl, wenn eine Datenbank mit sensiblen Daten geöffnet ist und auf den Rechner über das Internet zugegriffen werden kann.

Die so schnelle Programmierung einer neuen Version finde ich super - Chapeau! Ich werde sie vermutlich heute ausprobieren und mich melden.

Allerbesten Dank!!

R2D2Z

**Comment by r2d2z** [comment]
Hallo Rookiestyle,

der Link [Version 3.2.2.1](https://github.com/Rookiestyle/LockAssist/releases/tag/untagged-86e695aefb77bfb5dc7f). funktioniert nicht. Was muss ich tun?

R2D2Z

**Comment by Rookiestyle** [comment]
Der Link sollte zum Release führen, bei mir tut er das.
Dort findest du unter Assets die Datei *LockAssist.plgx*, mit der du deine aktuell genutzte Version ersetzen kannst

Alternativ: https://github.com/Rookiestyle/LockAssist/releases/download/untagged-86e695aefb77bfb5dc7f/LockAssist.plgx

**Comment by r2d2z** [comment]
Hallo Rookiestyle,

über den Alternativweg habe ich das Proberelease v 3.2.2.1 gefunden.

Das rockt!! Kann keinen Fehler erkennen.
Allenfalls ganz geringer Abzug in der c-Note: Wenn man einen Eintrag geöffnet hat und das Programm geht in den Softlock, ist der Hinweis "Softlock active. Click topmost form to deactivate" ausgegraut.

Viele Grüße und vielen Dank!

R2D2Z

[grafik](https://user-images.githubusercontent.com/132064596/235378357-4430fb1e-e966-4c42-8423-2d9e588ad0e9.png)
