### ISSUE TITLE
SoftLock: window inaccessible

### ISSUE THREAD

**Issue by caspadan** [Rookiestyle/LockAssist#14]
It's me again. :)
Not really a "bug" on your side, just a window needing to be "whitelisted". 

## Overview
When SoftLock is enabled and you need to unlock your database which is futher secured by the [OtpKeyProv](https://keepass.info/plugins.html#otpkeyprov) plugin, the window to input the OTP codes is locked by SoftLock 

![image](https://github.com/Rookiestyle/LockAssist/assets/61324156/175cef8f-bbf1-4201-97f5-b02bdedff541)

## Steps to Reproduce

1. Enable SoftLock. Ensure database is locked and softlock currently active
2. Unlock database (that also uses OtpKeyProv plugin for OTP codes) - do not unlock using the quick unlock feature.
3. OTP window is not accessible

## Expected Behavior
OtpKeyProv window should not be accessible during SoftLock

OS: Win10
KeePass Version: 2.54
Plugin Version: 3.3

**Comment by Rookiestyle** [comment]
Please attach a debug file. The file should contain all the window names and will help me in whitelisting it.

I don't have this plugin installed.

**Comment by caspadan** [comment]
Ok, got it, needed to go through the debug files as I didn't want to send it and the information was not there. Think I got it:
		<DebugEntry>
			<Message>Softlocked new window</Message>
			<Counter>1</Counter>
			<Severity>Info</Severity>
			<DateTimeUtc>20231012T105916Z</DateTimeUtc>
			<Parameters>
				<Param>**OtpKeyProv.Forms.OtpKeyPromptForm**</Param>
			</Parameters>
	
See attached debug file
[Debug_LockAssist_20231012T105719Z.xml.txt](https://github.com/Rookiestyle/LockAssist/files/12880691/Debug_LockAssist_20231012T105719Z.xml.txt)
