### ISSUE TITLE
Does LockAssist work with KeePass 2.5.5

### ISSUE THREAD

**Issue by bjm234** [Rookiestyle/LockAssist#15]
<img width="410" alt="png_17387" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/55402493-070f-4f5a-b02c-fdc4443f8d45">
<img width="414" alt="png_17385" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/bd2920e9-8830-4ae7-8631-4db1048703ff">
<img width="410" alt="png_17386" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/4fd41c42-cd61-46f8-b78c-4899d0b14c68">

LockAssist is set for one hour expiry, as test, to see LockAssist work.  Maybe, I have KeePass setting not supportive of LockAssist.  Maybe, my minimize KeePass to tray negates LockAssist. 
Maybe, I'm not understanding LockAssist Pin feature.   Do I need SoftLock enabled for LockAssist to work.  KeePass is set to lock work space after 300 seconds.   After 5 minutes.  KeePass locks requiring full master password. 
When I manually lock workspace.  LockAssist dialog presents and works.  Does LockAssist work with KeePass lock workspace timer.  Or, LockAssist only works with user interactive lock workspace?  head scratch Thanks

**Comment by Rookiestyle** [comment]
I want to verify my understanding

Scenario 1:
1. KeePass will lock after 5 minutes
2. Quick Unlock expiry time is 1 hour
3. You minimize KeePass to try.
4. You wait 5 minutes, KeePass is in tray and locked now
5. You reactive KeePass from tray
6. You must unlock with the full masterkey, Quick Unlock is not possible


Scenario 2:
1. KeePass will lock after 5 minutes
2. Quick Unlock expiry time is 1 hour
4. You wait 5 minutes, KeePass is locked now
6. You can unlock with Quick Unlock 

Is it like that?
Does the behaviour change if you deactivate Quick Unlock expiry time?


Please post screenshots from `Tools - Options - Security` and `Tools - Options - Interface (1)` and [attach a debug file](https://github.com/Rookiestyle/LockAssist/wiki/Create-a-debugfile#gui-plugin-options) for the scenario that does not work

**Comment by bjm234** [comment]
Hello
I was about to delete/edit my post...when I found your reply.  
I wish I could verify my understanding. 
~ took me a few more head scratches ~ 
LockAssist is now performing, as I had imagined.
**Thanks**
<img width="398" alt="png_17405" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/00b91d06-4461-4f40-9485-fe350abe3853">
<img width="398" alt="png_17406" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/446a8b13-4e6a-4e20-ad52-889a27153ce2">
<img width="394" alt="png_17407" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/18d7f11c-e40d-42d2-9f19-6390ebd2c320">
<img width="420" alt="png_17409" src="https://github.com/Rookiestyle/LockAssist/assets/25015553/56560e2d-f4c0-4c94-b6d8-fcb537a092c3">
