### ISSUE TITLE
SoftLock-QuickUnlock integration

### ISSUE THREAD

**Issue by surf08** [Rookiestyle/LockAssist#16]
SoftLock's QuickUnlock should asks for prompt master password after 1 failed attempt

**Comment by Rookiestyle** [comment]
Why?

Softlock allows you to do Auto-Type, ...
This would not change if the plugin requested the masterkey after 1 failed attempt.

**Comment by Rookiestyle** [comment]
SoftLock aims to protect you from shoulder-surfers and from leaving your workspace unattended.

If you are afraid from bruteforcing the pin while you're away, you can use the expiry time.
Once reached, you need to provide the complete masterkey
![image](https://github.com/Rookiestyle/LockAssist/assets/36454520/a418787b-4ec3-48ed-ac41-c7d8463a96e8)
