### ISSUE TITLE
lost "LockAssist - Quick Unlock" entry

### ISSUE THREAD

**Issue by popovn** [Rookiestyle/LockAssist#6]
As you write on
https://github.com/Rookiestyle/LockAssist/wiki/Quick-Unlock#quick-unlock-entry

'LockAssist - Quick Unlock' ........, it does not need to be in the rootgroup

if i move this entry in any group - i see error , that plugin cant find it

**Comment by Rookiestyle** [comment]
I cannot reproduce that.

When exactly is the error shown?
What is the exact error message?

Please show a screenshot of the message and please also attach a debug file as described here: https://github.com/Rookiestyle/LockAssist/wiki/Create-a-debugfile#gui-plugin-options

**Comment by popovn** [comment]
Change location of 'LockAssist - Quick Unlock' to "_work" folder - lock - unlock
everything is good

Change location of 'LockAssist - Quick Unlock' to "Maintenance" folder - lock - unlock
![изображение](https://user-images.githubusercontent.com/14332147/147383616-ad8bfad5-1ccf-4c9e-a67e-dd50dac4f7ce.png)
[Debug_LockAssist_20211225T091318Z.xml.txt](https://github.com/Rookiestyle/LockAssist/files/7775750/Debug_LockAssist_20211225T091318Z.xml.txt)
