### ISSUE TITLE
Minimize locking. Press Enter to still open the entry and toolbar clicking still works. It needs to be fixed

### ISSUE THREAD

**Issue by vipei** [Rookiestyle/LockAssist#8]

**Comment by Rookiestyle** [comment]
I can reproduce the toolbar button issue and will work an a fix.

I can't reproduce opening an entry if SoftLock is active.
Please provide more detailed instruction show to reproduce this and - if possible - a test database

I performed these 2 tests:

Test 1
Select an entry 
Wait for SoftLock to become active 
Press [Enter]
Result => I was asked to enter the Quick Unlock PIN.

Test 2
Select an entry 
Minimize KeePass (KeePass gets softlocked by doing that)
Restore KeePass
Press [Enter]
Result => I was asked to enter the Quick Unlock PIN.

For test 2 it did not matter whether KeePass was minimized to try or to taskbar

**Comment by vipei** [comment]
![newscreen45791515](https://user-images.githubusercontent.com/49584327/148405471-08f295af-86db-48fb-980e-d0ec994975f2.jpg)

**Comment by Rookiestyle** [comment]
I need to know the password for your file test.kdbx

**Comment by vipei** [comment]
pw:1

**Comment by Rookiestyle** [comment]
I still can't reproduce this.

Do you use LockAssist version 3.1.2?

Please do the following:
* Activate debug mode for LockAssist as described here: https://github.com/Rookiestyle/LockAssist/wiki/Create-a-debugfile#gui-plugin-options
* Reproduce the issue
* Deactivate debug mode
* Close KeePass
* Attach the debug file here

**Comment by Rookiestyle** [comment]
I figured out a way to reproduce this and will release a fix soon

**Comment by vipei** [comment]
[Debug_LockAssist_20220107T000930Z.zip](https://github.com/Rookiestyle/LockAssist/files/7825423/Debug_LockAssist_20220107T000930Z.zip)
I used 3.1.2

**Comment by Rookiestyle** [comment]
Please try the attached version, reproduce the issue and attach the debug file.

[LockAssist.zip](https://github.com/Rookiestyle/LockAssist/files/7828044/LockAssist.zip)

**Comment by vipei** [comment]
White screen, stuck




&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rookiestyle/LockAssist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Rookiestyle/LockAssist] Minimize locking. Press Enter to still open the entry and toolbar clicking still works. It needs to be fixed (Issue #8)





 
Please try the attached version, reproduce the issue and attach the debug file.
 
LockAssist.zip
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Rookiestyle** [comment]
Please use the attached version, try to reproduce the issue and attach the debug file.
[LockAssist.zip](https://github.com/Rookiestyle/LockAssist/files/7828247/LockAssist.zip)


Hopefully you can't reproduce the issue now.

**Comment by vipei** [comment]
It worked so well this time. You're so good

**Comment by vipei** [comment]
> It worked so well this time. You're so good Message ID: ***@***.***&gt;

New problem, minimize window lock after directly press ESC to open database
